[package]
name = "cryptoexchange"
version = "0.2.0"
authors = ["Denis Kolodin <denis.kolodin@xdev.re>", "Ilya Bogdanov <ilya.bogdanov@xdev.re>"]

[dependencies]
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
exonum = "0.9"
